### ISSUE TITLE
Ranger abilities bugged

### ISSUE THREAD

**Issue by Escherjem** [algnc/dcc-crawl-classes#10]
The climb, sneak and hide, survival, and strider abilities on the ranger sheet are locked at +1.

**Comment by algnc** [comment]
Assign for review

**Comment by algnc** [comment]
Fixed in .0.0.8

**Comment by Necrotech242** [comment]
Seems broken again =(

**Comment by algnc** [comment]
Sorry, should be fixed now. Broke when I tried adjusting for the new roll dialog

**Comment by Necrotech242** [comment]
Nice! Great job!
