### ISSUE TITLE
data.data.class.className not reflecting class name

### ISSUE THREAD

**Issue by woodwardj** [algnc/dcc-crawl-classes#13]
I am not sure if it would ever cause an issue while playing, but setting to one of these class sheets only updates data.data.details.sheetClass but leaves whatever the previous class was in the actor data.class.className.   I was using these classes as a template for adding other classes and found that I needed to use this.actor.update() to update className.

**Comment by algnc** [comment]
Yeah, something broke recently. I will take a look

**Comment by algnc** [comment]
@woodwardj it seems to be working OK for me. Where are you seeing it not set?

**Comment by algnc** [comment]
@woodwardj nm, I found it. working on fixes now. not sure why names aren't displaying correclty in sheet dialog

**Comment by algnc** [comment]
Fixed in #14
