### ISSUE TITLE
[REQUEST] Include Orc Class from Issue 5

### ISSUE THREAD

**Issue by justinthejaguar** [algnc/dcc-crawl-classes#4]
Hi, I was talking with someone else on the Foundry Discord who would be interested to see the Orc from Issue 5 of Crawl! included in your module. Is that something you would be interested in doing?

**Comment by algnc** [comment]
Yeah for sure!

**Comment by JohnnyGreenFace** [comment]
Nice, I am that other guy on the discord.

**Comment by algnc** [comment]
Fixed in #6
